name:                zen2-highlight-logs
version:             0.1.0.0
github:              "davecturner/zen2-highlight-logs"
license:             BSD3
author:              "David Turner"
maintainer:          "dave.c.turner@gmail.com"
copyright:           "2018 David Turner"

description:         Please see the README on GitHub at <https://github.com/davecturner/zen2-highlight-logs#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- bytestring
- conduit
- resourcet
- attoparsec
- word8
- text
- ansi-terminal
- unordered-containers
- hashable
- mtl

ghc-options:
- -Wall -Werror


library:
  source-dirs: src

executables:
  zen2-highlight-logs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zen2-highlight-logs

tests:
  zen2-highlight-logs-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zen2-highlight-logs
    - hspec
